Update nginxvh

diff --git a/nginxvh b/nginxvh
--- a/nginxvh
+++ b/nginxvh
@@ -1,27 +1,37 @@
 #!/bin/bash
 
+IS_ROOT_RUNNING=$(groups | grep -i 'root')
+
+if [ -z "$IS_ROOT_RUNNING" ]; then
+	echo 'root privileges required!'
+	exit 1
+fi
+
 NGINX_EXISTS=$(which nginx 2>/dev/null)
 
 if [ -z "$NGINX_EXISTS" ]; then
-  echo 'nginx should be installed to use this command.'
-  printf 'Do you want to install it now? [Y/n]: '
-  read WANT_INSTALL_NGINX
-  if [ -z "$WANT_INSTALL_NGINX" ]; then
-    sudo apt install nginx -y
-  else
-    WANT_INSTALL_NGINX=$(echo "$WANT_INSTALL_NGINX" | grep -i 'y')
-    if [ -z "$WANT_INSTALL_NGINX" ]; then
-      echo 'Aborting.'
-      exit 1
-    else
-      sudo apt install nginx -y
-    fi
-  fi
+	echo 'nginx should be installed to use this command.'
+	printf 'Do you want to install it now? [Y/n]: '
+	read WANT_INSTALL_NGINX
+	if [ -z "$WANT_INSTALL_NGINX" ]; then
+		apt install nginx -y
+	else
+		WANT_INSTALL_NGINX=$(echo "$WANT_INSTALL_NGINX" | grep -i 'y')
+		if [ -z "$WANT_INSTALL_NGINX" ]; then
+			echo 'Aborting.'
+			exit 1
+		else
+			apt install nginx -y
+		fi
+	fi
 fi
 
-if [ $# -lt 3 ]
+if [ $# -lt 2 ]
 then
-	echo 'Usage: nginxvh <virtual_host_name> <html|php|wordpress|laravel|remove> <port>'
+	echo 'Usage: nginxvh <virtual_host_name> <html|php|wordpress|laravel|remove> [<port>]'
+	echo ''
+	echo 'Where:'
+	echo "\tport: optional only with remove parameter, otherwise required!"
 else
 	if [ $2 == 'remove' ]
 	then
@@ -30,6 +40,11 @@ else
 		rm -R /var/www/$1
 		service nginx restart
 	else
+		if [ $# -lt 3 ]
+		then
+			echo 'Fatal Error: missing port.'
+			exit 1
+		fi
 		WWWUSER='root'
 		PHPV=$(php -v | grep -o -E 'PHP [0-9]+.[0-9]+' | tr [:upper:] [:lower:])
 		ISFMW=($2 == 'wordpress' or $2 == 'laravel')
@@ -97,11 +112,17 @@ else
 		mkdir /var/www/$1
 		if [ $2 == 'php' ]
 		then
-			echo '<?php phpinfo(); ?>' >> /var/www/$1/index.php
+			echo '<?php phpinfo();' >> /var/www/$1/index.php
 		else
 			if [ $2 == 'html' ]
 			then
 				echo '<h1>It Works!</h1>' >> /var/www/$1/index.html
+			else
+				if [ $ISFMW ]
+				then
+					mkdir /var/www/$1/public
+					echo '<?php phpinfo();' >> /var/www/$1/public/index.php
+				fi
 			fi
 		fi
 		ln -s $HOSTPATH /etc/nginx/sites-enabled/$1
